baseURL = ''
languageCode = 'en-us'
title = 'Brent F. Sanderson'
theme = 'hugo-theme-diary' 
[[menu.main]]
    name = 'Categories'
    url = '/tags'
    weight = 1
[[menu.main]]
    name = 'About Me'
    url = '/aboutme'
    weight = 2
[[menu.main]]
    name = 'Subscribe'
    url = 'https://buttondown.com/sanderson'
    weight = 3
 
 