baseURL = ''
languageCode = 'en-us'
title = 'Brent F. Sanderson'
theme = 'hugo-theme-diary' 
[[menu.main]]
    name = 'Categories'
    url = '/categories'
    weight = 2
[[menu.main]]
    name = 'About Me'
    url = '/aboutme'
    weight = 1
[params]
	text_color = "red"
 
 